# This file defines the menus on the website. See the documentation for
# details: https://docs.bolt.cm/configuration/menus

main:
  - label: accueil
    link: '#home'
    class: data-scroll-to
  - label: accrobranche
    submenu:
        - link: entry/213
        - link: entry/214
        - link: entry/215
        - link: entry/216
  - link: entry/217

  - label: groupes
    submenu:
        - link: entry/208
        - link: entry/209
        - link: entry/210
        - link: entry/211
        - link: entry/212
  - label: tarifs
    link: '#tarifs'
    class: data-scroll-to
  - label: contact horaires
    link: '#contact'
    class: data-scroll-to


foo: bar